// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, ".env") });

export default defineConfig({
  schema: "src/schema/prisma/schema.prisma",
  migrations: {
    path: "src/schema/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
